/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedTravelCounterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCountries"
      | "getEncryptedCountryCount"
      | "hasInitialized"
      | "protocolId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CountryCountAdded" | "CountryCountDecrypted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addCountries",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedCountryCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasInitialized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addCountries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedCountryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export namespace CountryCountAddedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryCountDecryptedEvent {
  export type InputTuple = [user: AddressLike, decryptedCount: BigNumberish];
  export type OutputTuple = [user: string, decryptedCount: bigint];
  export interface OutputObject {
    user: string;
    decryptedCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedTravelCounter extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedTravelCounter;
  waitForDeployment(): Promise<this>;

  interface: EncryptedTravelCounterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCountries: TypedContractMethod<
    [encryptedCountryCount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEncryptedCountryCount: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  hasInitialized: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCountries"
  ): TypedContractMethod<
    [encryptedCountryCount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedCountryCount"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "hasInitialized"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "CountryCountAdded"
  ): TypedContractEvent<
    CountryCountAddedEvent.InputTuple,
    CountryCountAddedEvent.OutputTuple,
    CountryCountAddedEvent.OutputObject
  >;
  getEvent(
    key: "CountryCountDecrypted"
  ): TypedContractEvent<
    CountryCountDecryptedEvent.InputTuple,
    CountryCountDecryptedEvent.OutputTuple,
    CountryCountDecryptedEvent.OutputObject
  >;

  filters: {
    "CountryCountAdded(address,uint256)": TypedContractEvent<
      CountryCountAddedEvent.InputTuple,
      CountryCountAddedEvent.OutputTuple,
      CountryCountAddedEvent.OutputObject
    >;
    CountryCountAdded: TypedContractEvent<
      CountryCountAddedEvent.InputTuple,
      CountryCountAddedEvent.OutputTuple,
      CountryCountAddedEvent.OutputObject
    >;

    "CountryCountDecrypted(address,uint256)": TypedContractEvent<
      CountryCountDecryptedEvent.InputTuple,
      CountryCountDecryptedEvent.OutputTuple,
      CountryCountDecryptedEvent.OutputObject
    >;
    CountryCountDecrypted: TypedContractEvent<
      CountryCountDecryptedEvent.InputTuple,
      CountryCountDecryptedEvent.OutputTuple,
      CountryCountDecryptedEvent.OutputObject
    >;
  };
}
